### ISSUE TITLE
Good job with the CSS code structure. A suggestion is to indent each property inside of the selector body.

### ISSUE THREAD

**Issue by josephtkim** [devnixio/teacozy#5]
The CSS code looks great, but one formatting practice to follow is to indent inner code. For instance,

```css
body {
  margin: 0;
  background-color: black;
  font-size: 22px;
  text-align: center;
  font-family: "Helvetica", sans-serif;
  color: seashell;
}
```

This is good practice to follow for code design and can make the code more readable and maintainable.
